---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-play-demo-02-dev
  namespace: janus-argocd
  labels:
    # argocd/app-name: demo-play-demo-02-dev
    wzhlab.top/app-name: demo-play-demo-02-dev
  annotations:
    # argocd/app-name: demo-play-demo-02-dev
    wzhlab.top/app-name: demo-play-demo-02-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/nepdemo/demo-play-demo-02-gitops.git
    targetRevision: wzh-2025.05
    path: ./helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-play
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
