---
apiVersion: v1
kind: Secret
metadata:
  name: demo-play-demo-02-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/nepdemo/demo-play-demo-02-gitops.git
